<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Винтажная бронзовая ваза',
                'slug' => 'vintazhnaya-bronzovaya-vaza',
                'code' => 'Арт-В24318',
                'price' => 52000,
                'image' => 'week_product-1.png',
                'is_new' => true,
                'order' => 1,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Модерн',
                'city' => 'Москва',
                'century' => 'XX век',
                'country' => 'Франция',
                'images' => ['week_product-1.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2025-01-15',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [1, 26],
            ],
            [
                'name' => 'Антикварный комод маркетри',
                'slug' => 'antikvarnyj-komod-marketri',
                'code' => 'Арт-К24502',
                'price' => 148000,
                'image' => 'week_product-2.png',
                'is_new' => true,
                'order' => 2,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Барокко',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Италия',
                'images' => ['week_product-2.png', 'product1-2.png', 'product1-3.png', 'product1-4.png'],
                'created_date' => '2025-02-10',
                'discount' => 40,
                'status' => 'available',
                'category_ids' => [23],
            ],
            [
                'name' => 'Французское кресло Louis XV',
                'slug' => 'francuzskoe-kreslo-louis-xv',
                'code' => 'Арт-К24637',
                'price' => 89000,
                'image' => 'week_product-3.png',
                'is_new' => true,
                'order' => 3,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Рококо',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Франция',
                'images' => ['week_product-3.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2025-01-20',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [2],
            ],
            [
                'name' => 'Старинный дубовый шкаф',
                'slug' => 'starinnyj-dubovyj-shkaf',
                'code' => 'Арт-Ш24789',
                'price' => 195000,
                'image' => 'week_product-4.png',
                'is_new' => true,
                'order' => 4,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Готический',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Германия',
                'images' => ['week_product-4.png', 'product1-2.png', 'product1-3.png', 'product1-4.png'],
                'created_date' => '2025-02-05',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [1],
            ],
            [
                'name' => 'Буфет в стиле Чиппендейл',
                'slug' => 'bufet-v-stile-chippendejl',
                'code' => 'Арт-Б24801',
                'price' => 167000,
                'image' => 'week_product-5.png',
                'is_new' => true,
                'order' => 5,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Чиппендейл',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Англия',
                'images' => ['week_product-5.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2025-01-25',
                'discount' => 0,
                'status' => 'coming_soon',
                'category_ids' => [4],
            ],
            [
                'name' => 'Винтажное зеркало в раме',
                'slug' => 'vintazhnoe-zerkalo-v-rame',
                'code' => 'Арт-З24912',
                'price' => 73000,
                'image' => 'week_product-6.png',
                'is_new' => true,
                'order' => 6,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Ампир',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Франция',
                'images' => ['week_product-6.png', 'product1-2.png', 'product1-3.png', 'product1-4.png'],
                'created_date' => '2025-02-12',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [11],
            ],
            [
                'name' => 'Антикварная люстра',
                'slug' => 'antikvarnaya-lyustra',
                'code' => 'Арт-Л25023',
                'price' => 124000,
                'image' => 'week_product-7.png',
                'is_new' => true,
                'order' => 7,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Барокко',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Италия',
                'images' => ['week_product-7.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2025-01-30',
                'discount' => 0,
                'status' => 'sold',
                'category_ids' => [9],
            ],
            [
                'name' => 'Резной столик-консоль',
                'slug' => 'reznoj-stolik-konsol',
                'code' => 'Арт-С25134',
                'price' => 98000,
                'image' => 'week_product-8.png',
                'is_new' => true,
                'order' => 8,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Рококо',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Франция',
                'images' => ['week_product-8.png', 'product1-2.png', 'product1-3.png', 'product1-4.png'],
                'created_date' => '2025-02-08',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [3, 11],
            ],
            [
                'name' => 'Винтажный книжный шкаф',
                'slug' => 'vintazhnyj-knizhnyj-shkaf',
                'code' => 'Арт-Ш25245',
                'price' => 186000,
                'image' => 'antique_1.png',
                'is_new' => false,
                'order' => 9,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Викторианский',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Англия',
                'images' => ['antique_1.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2024-12-15',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [1, 6],
            ],
            [
                'name' => 'Старинная витрина',
                'slug' => 'starinnaya-vitrina',
                'code' => 'Арт-В25356',
                'price' => 142000,
                'image' => 'antique_2.png',
                'is_new' => false,
                'order' => 10,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Ампир',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Франция',
                'images' => ['antique_2.png', 'product1-2.png', 'product1-3.png', 'product1-4.png'],
                'created_date' => '2024-12-20',
                'discount' => 0,
                'status' => 'reserved',
                'category_ids' => [5],
            ],
            [
                'name' => 'Мягкое кресло в бархате',
                'slug' => 'myagkoe-kreslo-v-barhate',
                'code' => 'Арт-К25467',
                'price' => 76000,
                'image' => 'antique_3.png',
                'is_new' => false,
                'order' => 11,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Модерн',
                'city' => 'Москва',
                'century' => 'XX век',
                'country' => 'Бельгия',
                'images' => ['antique_3.png', 'product1-2.png', 'product1-3.png', 'product1-4.png', 'product1-5.png'],
                'created_date' => '2024-11-25',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [2],
            ],
            [
                'name' => 'Обеденный стол из массива',
                'slug' => 'obedennyj-stol-iz-massiva',
                'code' => 'Арт-С25578',
                'price' => 213000,
                'image' => 'tables-1.jpg',
                'is_new' => false,
                'order' => 12,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Английский',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Англия',
                'images' => ['tables-1.jpg', 'tables-2.jpg', 'tables-3.jpg', 'tables-4.jpg'],
                'created_date' => '2024-12-05',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [3, 10],
            ],
            [
                'name' => 'Старинные часы напольные',
                'slug' => 'starinnye-chasy-napolnye',
                'code' => 'Арт-Ч25689',
                'price' => 156000,
                'image' => 'piano-1.jpg',
                'is_new' => false,
                'order' => 13,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Английский',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Англия',
                'images' => ['piano-1.jpg', 'piano-2.jpg', 'piano-3.jpg', 'piano-4.jpg', 'piano-5.jpg'],
                'created_date' => '2024-11-30',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [12],
            ],
            [
                'name' => 'Винтажная банкетка',
                'slug' => 'vintazhnaya-banketka',
                'code' => 'Арт-Б25790',
                'price' => 64000,
                'image' => 'soft-1.jpg',
                'is_new' => false,
                'order' => 14,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Модерн',
                'city' => 'Москва',
                'century' => 'XX век',
                'country' => 'Франция',
                'images' => ['soft-1.jpg', 'soft-2.jpg', 'soft-3.jpg', 'soft-4.jpg'],
                'created_date' => '2024-12-10',
                'discount' => 0,
                'status' => 'restoration',
                'category_ids' => [2],
            ],
            [
                'name' => 'Антикварная ширма',
                'slug' => 'antikvarnaya-shirma',
                'code' => 'Арт-Ш25801',
                'price' => 87000,
                'image' => 'dresser-1.jpg',
                'is_new' => false,
                'order' => 15,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Шинуазри',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Китай',
                'images' => ['dresser-1.jpg', 'dresser-2.jpg', 'dresser-3.jpg', 'dresser-4.jpg', 'dresser-5.jpg'],
                'created_date' => '2024-11-20',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [19, 21],
            ],
            [
                'name' => 'Комод с мраморной столешницей',
                'slug' => 'komod-s-mramornoj-stoleshnicej',
                'code' => 'Арт-К25912',
                'price' => 178000,
                'image' => 'dresser-2.jpg',
                'is_new' => false,
                'order' => 16,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Ампир',
                'city' => 'Тольятти',
                'century' => 'XIX век',
                'country' => 'Франция',
                'images' => ['dresser-2.jpg', 'dresser-3.jpg', 'dresser-4.jpg', 'dresser-5.jpg'],
                'created_date' => '2024-12-18',
                'discount' => 0,
                'status' => 'custom_order',
                'category_ids' => [23],
            ],
            [
                'name' => 'Старинная картина в раме',
                'slug' => 'starinnaya-kartina-v-rame',
                'code' => 'Арт-К26023',
                'price' => 92000,
                'image' => 'irland-1.jpeg',
                'is_new' => false,
                'order' => 17,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Романтизм',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Италия',
                'images' => ['irland-1.jpeg', 'irland-2.jpeg', 'irland-3.jpeg', 'irland-4.jpeg', 'irland-5.jpeg'],
                'created_date' => '2024-11-15',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [18],
            ],
            [
                'name' => 'Секретер с инкрустацией',
                'slug' => 'sekreter-s-inkrustaciej',
                'code' => 'Арт-С26134',
                'price' => 168000,
                'image' => 'dresser-3.jpg',
                'is_new' => false,
                'order' => 18,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Барокко',
                'city' => 'Москва',
                'century' => 'XVIII век',
                'country' => 'Италия',
                'images' => ['dresser-3.jpg', 'dresser-4.jpg', 'dresser-5.jpg', 'dresser-6.jpg'],
                'created_date' => '2024-12-22',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [23, 6],
            ],
            [
                'name' => 'Камин старинный из мрамора',
                'slug' => 'kamin-starinnyj-iz-mramora',
                'code' => 'Арт-К26245',
                'price' => 425000,
                'image' => 'repair-1.jpg',
                'is_new' => false,
                'order' => 19,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Классицизм',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Франция',
                'images' => ['repair-1.jpg', 'repair-2.jpg', 'repair-3.jpg', 'repair-4.jpg', 'repair-5.jpg'],
                'created_date' => '2024-11-10',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [13],
            ],
            [
                'name' => 'Скульптура бронзовая',
                'slug' => 'skulptura-bronzovaya',
                'code' => 'Арт-С26356',
                'price' => 134000,
                'image' => 'podsnejnik-1.jpg',
                'is_new' => false,
                'order' => 20,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Модерн',
                'city' => 'Москва',
                'century' => 'XX век',
                'country' => 'Франция',
                'images' => ['podsnejnik-1.jpg', 'podsnejnik-2.jpg', 'podsnejnik-3.jpg', 'podsnejnik-4.jpg'],
                'created_date' => '2024-12-28',
                'discount' => 0,
                'status' => 'sold',
                'category_ids' => [14],
            ],
            [
                'name' => 'Диван Честерфилд',
                'slug' => 'divan-chesterfild',
                'code' => 'Арт-Д26467',
                'price' => 196000,
                'image' => 'soft-2.jpg',
                'is_new' => false,
                'order' => 21,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Английский',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Англия',
                'images' => ['soft-2.jpg', 'soft-3.jpg', 'soft-4.jpg', 'soft-5.jpg', 'soft-6.jpg'],
                'created_date' => '2024-11-05',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [2],
            ],
            [
                'name' => 'Прихожая с вешалкой',
                'slug' => 'prihozhaya-s-veshalkoj',
                'code' => 'Арт-П26578',
                'price' => 118000,
                'image' => 'buffets-1.jpg',
                'is_new' => false,
                'order' => 22,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Модерн',
                'city' => 'Тольятти',
                'century' => 'XX век',
                'country' => 'Германия',
                'images' => ['buffets-1.jpg', 'buffets-2.jpg', 'buffets-3.jpg', 'buffets-4.jpg'],
                'created_date' => '2024-12-03',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [20],
            ],
            [
                'name' => 'Набор стульев венских',
                'slug' => 'nabor-stulev-venskih',
                'code' => 'Арт-С26689',
                'price' => 142000,
                'image' => 'dining-1.jpg',
                'is_new' => false,
                'order' => 23,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Венский',
                'city' => 'Москва',
                'century' => 'XIX век',
                'country' => 'Австрия',
                'images' => ['dining-1.jpg', 'dining-2.jpg', 'dining-3.jpg', 'dining-4.jpg', 'dining-5.jpg'],
                'created_date' => '2024-11-28',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [2, 10],
            ],
            [
                'name' => 'Комплект обеденный шинуазри',
                'slug' => 'komplekt-obedennyj-shinuazri',
                'code' => 'Арт-И24186',
                'price' => 280000,
                'image' => 'product1-3.png',
                'is_new' => false,
                'order' => 24,
                'description' => 'Описание товара носит информативный характер, экспертиза времени и места не проводилась',
                'style' => 'Шинуазри',
                'city' => 'Москва',
                'century' => 'XX век',
                'country' => 'Бельгия',
                'images' => ['product1-3.png', 'product1-4.png', 'product1-5.png', 'product-1-1.png', 'product1-2.png'],
                'created_date' => '2025-06-18',
                'discount' => 0,
                'status' => 'available',
                'category_ids' => [3, 10, 15, 19],
            ],
        ];

        foreach ($products as $productData) {
            $categoryIds = $productData['category_ids'];
            unset($productData['category_ids']);
            
            $product = Product::create($productData);
            $product->categories()->attach($categoryIds);
        }
    }
}
